from enum import StrEnum


class RecruitmentType(StrEnum):
    CIVIL_SERVICE_NATIONAL = "CIVIL_SERVICE_NATIONAL"
    CIVIL_SERVICE_PROVINCE = "CIVIL_SERVICE_PROVINCE"
    PUBLIC_INSTITUTION = "PUBLIC_INSTITUTION"
    SOE_STATE_GRID = "SOE_STATE_GRID"
    SOE_CENTRAL = "SOE_CENTRAL"
    SOE_LOCAL = "SOE_LOCAL"


class RecruitmentStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    UPCOMING = "UPCOMING"
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    EXAM = "EXAM"
    INTERVIEW = "INTERVIEW"
    RESULT = "RESULT"
    FINISHED = "FINISHED"
    CANCELLED = "CANCELLED"


class LocationType(StrEnum):
    WORK_LOCATION = "WORK_LOCATION"
    ORG_LOCATION = "ORG_LOCATION"
    EXAM_LOCATION = "EXAM_LOCATION"
    APPLICATION_SCOPE = "APPLICATION_SCOPE"


class LocationPrecision(StrEnum):
    NATIONWIDE = "NATIONWIDE"
    PROVINCE = "PROVINCE"
    CITY = "CITY"
    COUNTY = "COUNTY"
    MULTI_REGION = "MULTI_REGION"
    UNKNOWN = "UNKNOWN"


class SourceHealth(StrEnum):
    UNKNOWN = "UNKNOWN"
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    PAUSED = "PAUSED"


class CrawlStatus(StrEnum):
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
