"""initial schema

Revision ID: 77a9ec56a588
Revises: 
Create Date: 2026-09-15 10:17:16.221699
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77a9ec56a588'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrative_division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['administrative_division.id'], name=op.f('fk_administrative_division_parent_id_administrative_division')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_administrative_division')),
    sa.UniqueConstraint('code', 'valid_from', name='uq_division_code_version')
    )
    op.create_index(op.f('ix_administrative_division_code'), 'administrative_division', ['code'], unique=False)
    op.create_index(op.f('ix_administrative_division_level'), 'administrative_division', ['level'], unique=False)
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('organization_type', sa.String(length=80), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('province_code', sa.String(length=6), nullable=True),
    sa.Column('city_code', sa.String(length=6), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['organization.id'], name=op.f('fk_organization_parent_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_index(op.f('ix_organization_canonical_name'), 'organization', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_organization_city_code'), 'organization', ['city_code'], unique=False)
    op.create_index(op.f('ix_organization_province_code'), 'organization', ['province_code'], unique=False)
    op.create_table('source_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('authority_level', sa.String(length=30), nullable=False),
    sa.Column('province_code', sa.String(length=6), nullable=True),
    sa.Column('city_code', sa.String(length=6), nullable=True),
    sa.Column('adapter_key', sa.String(length=120), nullable=False),
    sa.Column('crawl_policy', sa.JSON(), nullable=False),
    sa.Column('interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.Enum('UNKNOWN', 'HEALTHY', 'DEGRADED', 'PAUSED', name='source_health', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_registry')),
    sa.UniqueConstraint('key', name=op.f('uq_source_registry_key'))
    )
    op.create_table('crawl_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED', name='crawl_status', native_enum=False), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_crawl_run_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_run'))
    )
    op.create_index(op.f('ix_crawl_run_source_id'), 'crawl_run', ['source_id'], unique=False)
    op.create_table('raw_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=160), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('parser_version', sa.String(length=80), nullable=True),
    sa.Column('parse_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_raw_document_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_document'))
    )
    op.create_index(op.f('ix_raw_document_content_hash'), 'raw_document', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_document_source_id'), 'raw_document', ['source_id'], unique=False)
    op.create_table('recruitment_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('recruitment_type', sa.Enum('CIVIL_SERVICE_NATIONAL', 'CIVIL_SERVICE_PROVINCE', 'PUBLIC_INSTITUTION', 'SOE_STATE_GRID', 'SOE_CENTRAL', 'SOE_LOCAL', name='recruitment_type', native_enum=False), nullable=False),
    sa.Column('audience_type', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('batch_no', sa.String(length=80), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'OPEN', 'CLOSED', 'EXAM', 'INTERVIEW', 'RESULT', 'FINISHED', 'CANCELLED', name='recruitment_status', native_enum=False), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_recruitment_batch_organization_id_organization')),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], name=op.f('fk_recruitment_batch_source_id_source_registry')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_batch'))
    )
    op.create_index(op.f('ix_recruitment_batch_application_end_at'), 'recruitment_batch', ['application_end_at'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_organization_id'), 'recruitment_batch', ['organization_id'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_publish_at'), 'recruitment_batch', ['publish_at'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_recruitment_type'), 'recruitment_batch', ['recruitment_type'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_source_id'), 'recruitment_batch', ['source_id'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_status'), 'recruitment_batch', ['status'], unique=False)
    op.create_index(op.f('ix_recruitment_batch_year'), 'recruitment_batch', ['year'], unique=False)
    op.create_table('exam_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('province_code', sa.String(length=6), nullable=True),
    sa.Column('city_code', sa.String(length=6), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['recruitment_batch.id'], name=op.f('fk_exam_event_batch_id_recruitment_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_event'))
    )
    op.create_index(op.f('ix_exam_event_batch_id'), 'exam_event', ['batch_id'], unique=False)
    op.create_index(op.f('ix_exam_event_city_code'), 'exam_event', ['city_code'], unique=False)
    op.create_index(op.f('ix_exam_event_event_type'), 'exam_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_exam_event_province_code'), 'exam_event', ['province_code'], unique=False)
    op.create_index(op.f('ix_exam_event_start_at'), 'exam_event', ['start_at'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_position_id', sa.String(length=160), nullable=True),
    sa.Column('position_code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('department', sa.String(length=300), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('education', sa.String(length=80), nullable=True),
    sa.Column('degree', sa.String(length=80), nullable=True),
    sa.Column('majors_raw', sa.Text(), nullable=True),
    sa.Column('political_status', sa.String(length=120), nullable=True),
    sa.Column('work_experience', sa.String(length=200), nullable=True),
    sa.Column('graduate_year', sa.String(length=80), nullable=True),
    sa.Column('age_requirement', sa.String(length=160), nullable=True),
    sa.Column('household_requirement', sa.String(length=200), nullable=True),
    sa.Column('other_requirements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['recruitment_batch.id'], name=op.f('fk_position_batch_id_recruitment_batch')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position')),
    sa.UniqueConstraint('batch_id', 'source_position_id', name='uq_position_batch_source_id')
    )
    op.create_index(op.f('ix_position_batch_id'), 'position', ['batch_id'], unique=False)
    op.create_index(op.f('ix_position_education'), 'position', ['education'], unique=False)
    op.create_index(op.f('ix_position_position_code'), 'position', ['position_code'], unique=False)
    op.create_index(op.f('ix_position_title'), 'position', ['title'], unique=False)
    op.create_table('revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('raw_document_id', sa.Integer(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['recruitment_batch.id'], name=op.f('fk_revision_batch_id_recruitment_batch')),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_document.id'], name=op.f('fk_revision_raw_document_id_raw_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revision')),
    sa.UniqueConstraint('batch_id', 'revision_no', name='uq_revision_batch_number')
    )
    op.create_index(op.f('ix_revision_batch_id'), 'revision', ['batch_id'], unique=False)
    op.create_table('position_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('province_code', sa.String(length=6), nullable=True),
    sa.Column('city_code', sa.String(length=6), nullable=True),
    sa.Column('location_type', sa.Enum('WORK_LOCATION', 'ORG_LOCATION', 'EXAM_LOCATION', 'APPLICATION_SCOPE', name='location_type', native_enum=False), nullable=False),
    sa.Column('precision', sa.Enum('NATIONWIDE', 'PROVINCE', 'CITY', 'COUNTY', 'MULTI_REGION', 'UNKNOWN', name='location_precision', native_enum=False), nullable=False),
    sa.Column('raw_text', sa.String(length=300), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['administrative_division.id'], name=op.f('fk_position_location_division_id_administrative_division')),
    sa.ForeignKeyConstraint(['position_id'], ['position.id'], name=op.f('fk_position_location_position_id_position')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_location'))
    )
    op.create_index('ix_position_location_area', 'position_location', ['province_code', 'city_code', 'precision'], unique=False)
    op.create_index(op.f('ix_position_location_city_code'), 'position_location', ['city_code'], unique=False)
    op.create_index(op.f('ix_position_location_division_id'), 'position_location', ['division_id'], unique=False)
    op.create_index(op.f('ix_position_location_location_type'), 'position_location', ['location_type'], unique=False)
    op.create_index(op.f('ix_position_location_position_id'), 'position_location', ['position_id'], unique=False)
    op.create_index(op.f('ix_position_location_precision'), 'position_location', ['precision'], unique=False)
    op.create_index(op.f('ix_position_location_province_code'), 'position_location', ['province_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_position_location_province_code'), table_name='position_location')
    op.drop_index(op.f('ix_position_location_precision'), table_name='position_location')
    op.drop_index(op.f('ix_position_location_position_id'), table_name='position_location')
    op.drop_index(op.f('ix_position_location_location_type'), table_name='position_location')
    op.drop_index(op.f('ix_position_location_division_id'), table_name='position_location')
    op.drop_index(op.f('ix_position_location_city_code'), table_name='position_location')
    op.drop_index('ix_position_location_area', table_name='position_location')
    op.drop_table('position_location')
    op.drop_index(op.f('ix_revision_batch_id'), table_name='revision')
    op.drop_table('revision')
    op.drop_index(op.f('ix_position_title'), table_name='position')
    op.drop_index(op.f('ix_position_position_code'), table_name='position')
    op.drop_index(op.f('ix_position_education'), table_name='position')
    op.drop_index(op.f('ix_position_batch_id'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_exam_event_start_at'), table_name='exam_event')
    op.drop_index(op.f('ix_exam_event_province_code'), table_name='exam_event')
    op.drop_index(op.f('ix_exam_event_event_type'), table_name='exam_event')
    op.drop_index(op.f('ix_exam_event_city_code'), table_name='exam_event')
    op.drop_index(op.f('ix_exam_event_batch_id'), table_name='exam_event')
    op.drop_table('exam_event')
    op.drop_index(op.f('ix_recruitment_batch_year'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_status'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_source_id'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_recruitment_type'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_publish_at'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_organization_id'), table_name='recruitment_batch')
    op.drop_index(op.f('ix_recruitment_batch_application_end_at'), table_name='recruitment_batch')
    op.drop_table('recruitment_batch')
    op.drop_index(op.f('ix_raw_document_source_id'), table_name='raw_document')
    op.drop_index(op.f('ix_raw_document_content_hash'), table_name='raw_document')
    op.drop_table('raw_document')
    op.drop_index(op.f('ix_crawl_run_source_id'), table_name='crawl_run')
    op.drop_table('crawl_run')
    op.drop_table('source_registry')
    op.drop_index(op.f('ix_organization_province_code'), table_name='organization')
    op.drop_index(op.f('ix_organization_city_code'), table_name='organization')
    op.drop_index(op.f('ix_organization_canonical_name'), table_name='organization')
    op.drop_table('organization')
    op.drop_index(op.f('ix_administrative_division_level'), table_name='administrative_division')
    op.drop_index(op.f('ix_administrative_division_code'), table_name='administrative_division')
    op.drop_table('administrative_division')
    # ### end Alembic commands ###
